### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by shazow** [anondotworld/anonworld#12]
An open source license adds protections for the author, contributors, and users.

I suggest a permissive license like MIT or Apache2 if you're optimizing for impact and not afraid of other projects reusing the code.

Can go in the GitHub UI, add new file, type `LICENSE` and it will give a bunch of templates, or I can send a PR.

**Comment by Slokh** [comment]
thanks, meant to do this but forgot

**Comment by shazow** [comment]
💚🐐
