### ISSUE TITLE
update design based on figma

### ISSUE THREAD

**Issue by Slokh** [anondotworld/anonworld#18]
https://www.figma.com/design/UKdLtH0isKn0jagjrqaVN3/Anoncast?node-id=18-1193&node-type=canvas&t=y3pyvzrC6wokSRtK-0

**Comment by moesalih** [comment]
looks like this one is already done?

**Comment by Owoskw** [comment]
Gm

**Comment by Owoskw** [comment]
Done

**Comment by Slokh** [comment]
> looks like this one is already done?

yep forgot to close
