### ISSUE TITLE
Fix this cast text display issue

### ISSUE THREAD

**Issue by Slokh** [anondotworld/anonworld#25]
![image](https://github.com/user-attachments/assets/d38363b5-fa72-4e40-81dc-88f2a36bffff)

https://warpcast.com/anoncast/0xf2388fcc

**Comment by Owoskw** [comment]
Good project

**Comment by jhonc-eth** [comment]
Normalize Text Before Rendering:

const sanitizedText = cast.text?.normalize("NFKC") || "Invalid text";
Apply .normalize("NFKC") to malformed strings before displaying them.

Ensure Proper Font Support: Use a font that supports full Unicode (e.g., Arial, sans-serif) in your CSS or Tailwind configuration:

fontFamily: {
  sans: ['Arial', 'Helvetica', 'sans-serif'],
}
