### ISSUE TITLE
Mobile posting doesn't work

### ISSUE THREAD

**Issue by Slokh** [anondotworld/anonworld#6]
Two different issues that are simultaneously happening:
1. Get's stuck on awaiting signature after signing message in wallet
2. Generating proof takes really long or causes blank screen.

For the second issue, this is likely because the circuit is just requiring too much processing power from the mobile device.

**Comment by Owoskw** [comment]
> Two different issues that are simultaneously happening:
> 
> 1. Get's stuck on awaiting signature after signing message in wallet
> 2. Generating proof takes really long or causes blank screen.
> 
> For the second issue, this is likely because the circuit is just requiring too much processing power from the mobile device.

**Comment by Owoskw** [comment]
Good project

**Comment by amit0365** [comment]
Generating proof is kiiled on an Air tab too. Confusing
