### ISSUE TITLE
What is https://api.uno.fun?

### ISSUE THREAD

**Issue by stevenjoe0906** [anondotworld/anonworld#67]
I have tried to google for uno/uno.fun but no results.
Is it a cloud service platform? How to sign up on it

**Comment by stevenjoe0906** [comment]
And its official site(I think) just displays this icon

![image](https://github.com/user-attachments/assets/9ca34740-d292-4bd6-bc21-0f336fea3f85)

**Comment by christopherwxyz** [comment]
Image upload moderation. Images pass through a vision model to make sure they are safe.

**Comment by alexpaden** [comment]
thoughts on replacing with https://platform.openai.com/docs/guides/moderation for public access?

**Comment by AndonMitev** [comment]
Hey @christopherwxyz, could you please share where we can apply for this service? I tried finding some information using the API URL but wasn’t successful.
