### ISSUE TITLE
Add a longer post feature

### ISSUE THREAD

**Issue by kevinj507** [anondotworld/anonworld#71]
More thoughtful posts (or pastas, stories) limited by 320 characters

Neynar supports long casts, X verified accounts should support up to 25k characters

**Comment by stevenjoe0906** [comment]
Hey @kevinj507 Try the [Tako](https://apps.apple.com/us/app/tako-high-tech-high-life/id6737880963) app
We're working on the long post feature; it will go live soon. You will be able to write 5,000 to 10,000 characters
