### ISSUE TITLE
[UI DESIGN] Implement nav navigation

### ISSUE THREAD

**Issue by 0xchsh** [anondotworld/anonworld#77]
Need new navigation ux since links are getting cluttered.

Designs: https://www.figma.com/design/UKdLtH0isKn0jagjrqaVN3/Anoncast?node-id=465-8563&t=L23dYS1e7WuV4cgK-1

![CleanShot 2024-11-26 at 21 51 42@2x](https://github.com/user-attachments/assets/fc724f1e-4a9d-4b65-88ee-99499a8aff46)

![CleanShot 2024-11-26 at 21 50 54@2x](https://github.com/user-attachments/assets/f564d545-b6c8-4ef6-a3e0-3aa4bd21c9a3)

**Comment by kekubhai** [comment]
is it still open I would like to work on this

**Comment by kekubhai** [comment]
hey man I worked on this today and this i show it looks : 
![image](https://github.com/user-attachments/assets/d244a42f-9c79-4f00-b4f6-fe0e1760cb16)
I have added the dropdown options and made it responsive with sidebar
